apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-service
  template:
    metadata:
      labels:
        app: simple-service
    spec:
      containers:
        - name: simple-service
          image: 241533159061.dkr.ecr.us-east-1.amazonaws.com/simple-service:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: simple-service-serv
spec:
  selector:
    app: simple-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer